---
language: node_js
node_js:
  - "0.10"
notifications:
  email: false
env:
  global:
    secure: "Agpt15O6pJtINwMpIlDy/KppHXK3dqk2MWKFf+4FM/d4dRkr7EP4DuL9K6jK\nvhQk3rzRN2D5xwv2oUyS4WBmnIvWZ+/Mb79nRsKWCIrgZ18w5O55n8UOs+C6\nJEtfzKR982RqQg2nmyu9pWIadnAvIpSFfJBvFieUldIIwWJTc1k="
    secure: "O6QiC0V5Dc6S5GA+azdx4F8cuhNgywbNgLAeYUcBHJz0HydpiSJDV9hzy6PN\nIn1C9CV66qvBgd6zYHaJ4okgfnuyDNbeRf4B9dWLZSjcYwx2ZU5zG5M1XsAR\n6DHxLqbgtMFk7RIJ7WhOlFJHCAxixyTN+82buRKJOnajAOzC7VE="