---
language: node_js
node_js:
  - "0.10"
notifications:
  email: false
env:
  global:
    secure: "Q8BaxImZ6Z9rTQ0ogLYYYmkegWpDQMEjGrVU6G7y/L4ktqz9tdSh9CVe5pU2\nVi2Z/uY1U337z3hOqpnKfJXHa/kkJGS3gCcviRyI8pumLmEC4xa5j4s5ikmH\nj2Ew75EMCWUjcsS6nkXgYS6rLZ5D6fbQa67U59Mn2y/JdXfnyRc="
    secure: "Y39+RMQG7hZ9DZ8OnLPOqRv/al1VvdUU14A1rr/wXV8VyUbP9ZUwaW9C8UbI\nDb9o3Axh4nx3wARIRF0NJZ27Vlh5ufQzGCUqPM9eCxBkq/SzSNUu8JPxFWAu\nhc/lYFyoXqMhETRAc9Fe8JGLnsLnLy17lT8yuiKarLJ+Mvnsdko="
    secure: "JntEH5er2ZxApReUS6YAOmNfbSvILVO8tI4R8LaWDIYrQ2DZDMxD4d+9A5vC\nEeyJbpLENgTu3j6Dpra0XPwb6DFWG1dvWGR9A/GeVPgeEFjWEoGBKaW1HwAo\nOu7J/yjT5wvkGszgkygirsAk6eYepEjxEfwweYUXOYlOe2Dp4w0="