---
language: node_js
node_js:
  - "0.10"
notifications:
  email: false
env:
  global:
    secure: "SChXYf9r/EYOjoSOdXYoftU5cooUXt2qQSqDnNc57bNd58/uUQhWcc3xm7bq\nSpOm1NkJyyj/3M24sQqqVsjN+goAfnDwhb4Mv/it2/KjAgtYUjWep4dDtAMt\n8OHoVceIvW4LQ2DCHIGXq9QtVoH+OX9VNfgV5xfHtelkAizRYJs="