---
language: node_js
node_js:
  - "0.10"
notifications:
  email: false
env:
  global:
    secure: "aUZ62tRrInqtg5GYtU62I2vPKCX2uitdq7Pm41YtxpRSd6nQSb060GqmYGSOlpbjdGJsstFFBtxlByK5Adqj7Js7kNnecI8px65BDZxUifRgWvr45aUL5A7uTy5fVS0F78kDOMNjvRHn/FvVrX6e/6miPyiPq4ynaeqxWUHUfn0="