---
language: node_js
node_js:
  - "0.10"
notifications:
  email: false
env:
  global:
    secure: "ICnIz+vOFChM1pP2wtQwm/c8tJtDpgBD3Rifyc2HDm85QVFatSn9aQW4D4+U\nKqm/Bnlskn+/CYjkwnEwp5ulo+yK37cxOzApYrN2VRPRSXFlZc12Zx432wij\n5oY+KgB6buuwpOcoKiJEoV8gHy6xiWrM9U5tnW53ognRxUw/Kco="
    secure: "U2gSWbVBiK0nO8OwKYH1E/5jH8rjPIdxyy3oScCkcm58gvf75f1XTzZEh5AP\nFNjyRj5K2OWCMp6DT+pTaZdlMyxZbV8DGKRGL9gFR1iLSG597oSw40OQeT1s\n63BNibwvwFpY41sch1vcDZgA9qciK+OKDItLoMYBz5/E99Y+LqA="